# key names for processing config file for OpenADR VEN agent
VEN_NAME = "ven_name"
VTN_URL = "vtn_url"
DEBUG = "debug"
CERT = "cert"
KEY = "key"
PASSPHRASE = "passphrase"
VTN_FINGERPRINT = "vtn_fingerprint"
SHOW_FINGERPRINT = "show_fingerprint"
CA_FILE = "ca_file"
VEN_ID = "ven_id"
DISABLE_SIGNATURE = "disable_signature"
VIP_ADDRESS = "vip_address"
PORT = "port"
SERVER_KEY = "server_key"
AGENT_PUBLIC = "agent_public"
AGENT_SECRET = "agent_secret"
